### ISSUE TITLE
Update Python script to OMPython 4.0.0

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelicaLibraryTesting#243]
## Issue

OMPython 4 no longer has function `FindBestOMCSession`.

```bash
File \"/OpenModelicaLibraryTesting/testmodel.py\", line 8, in <module>
        from OMPython import FindBestOMCSession, OMCSession, OMCSessionZMQ
 ImportError: cannot import name 'FindBestOMCSession' from 'OMPython'
```

We need to fix OMPython to 3.6 or update the scripts to work with 4.0.

**Comment by AnHeuermann** [comment]
@adpro How are Python dependencies like OMPython managed for our nightly tests?
If #244 get's merged we need to update them.

**Comment by adeas31** [comment]
This is strange. `sendExpression(loadModel(IDEAS,{"master"}), True)` looks perfectly fine.

I tried the following with OMPython 4.0.0 and it worked fine.

```
from OMPython import OMCSessionZMQ
omc = OMCSessionZMQ()
omc.sendExpression('loadModel(IDEAS,{"3.0.0"})')
```

I used version `3.0.0` since that's what I got from package manager. With `master` I get,

```
Traceback (most recent call last):
  File "C:\OpenModelica\OMPython\test.py", line 3, in <module>
    omc.sendExpression('loadModel(IDEAS,{"master"})')
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenModelica\OMPython\OMPython\OMCSession.py", line 760, in sendExpression
    raise OMCSessionException(msg)
OMPython.OMCSession.OMCSessionException: [OMC log for 'sendExpression(loadModel(IDEAS,{"master"}), True)']: [scripting:error:184] Failed to load package IDEAS (master) using MODELICAPATH C:/Users/adeas31/AppData/Roaming/.openmodelica/libraries/.
```

Perhaps some issue with quoting of string?
@syntron any idea?
